-- Danu Warisman
-- 1031222400041

-- soal1
SELECT j.ID_THEATER AS NOMOR_TEATER,
       f.JUDUL AS JUDUL_FILM,
       SUM(t.HARGA) AS TOTAL_PENDAPATAN
FROM TRANSAKSI tr
JOIN JADWAL j ON tr.ID_JADWAL = j.ID_JADWAL
JOIN FILM f ON j.ID_FILM = f.ID_FILM
JOIN INVENTORI i ON tr.ID_INVENTORI = i.ID_INVENTORI
JOIN THEATER t ON i.ID_THEATER = t.ID_THEATER
GROUP BY j.ID_THEATER, f.JUDUL
HAVING SUM(t.HARGA) > 150000
ORDER BY TOTAL_PENDAPATAN DESC;

-- soal2
    SELECT f.JUDUL AS JUDUL_FILM,
           COUNT(tr.KODE_PEMESANAN) AS TOTAL_TIKET_TERJUAL
    FROM TRANSAKSI tr
    JOIN JADWAL j ON tr.ID_JADWAL = j.ID_JADWAL
    JOIN FILM f ON j.ID_FILM = f.ID_FILM
    WHERE tr.STATUS = 'pesan'
    GROUP BY f.JUDUL
    HAVING COUNT(tr.KODE_PEMESANAN) = (
        SELECT MAX(cnt) FROM (
            SELECT COUNT(tr2.KODE_PEMESANAN) AS cnt
            FROM TRANSAKSI tr2
            JOIN JADWAL j2 ON tr2.ID_JADWAL = j2.ID_JADWAL
            WHERE tr2.STATUS = 'pesan'
            GROUP BY j2.ID_FILM
        )
    );
    
-- soal3
SELECT ID_THEATER AS NOMOR_TEATER,
       AVG(HARGA) AS "AVG(HARGA)"
FROM THEATER
WHERE ID_THEATER IN (
    SELECT DISTINCT ID_THEATER FROM INVENTORI
    WHERE ID_INVENTORI IN (
        SELECT ID_INVENTORI FROM TRANSAKSI
    )
)
GROUP BY ID_THEATER
ORDER BY ID_THEATER;

-- soal4
SELECT f.JUDUL AS JUDUL_FILM,
       j.ID_THEATER AS NOMOR_TEATER,
       COUNT(j.ID_JADWAL) AS JUMLAH_DIPUTAR
FROM JADWAL j
JOIN FILM f ON j.ID_FILM = f.ID_FILM
WHERE f.JUDUL = 'Habibie Ainun 3'
GROUP BY f.JUDUL, j.ID_THEATER
ORDER BY j.ID_THEATER;